### ISSUE TITLE
Unify configiration of jobs and groups

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-job#112]
Configuration of jobs and groups should look the same. Instead groups store their children in "jobs" map, and "jobs" - in "dependsOn" list. Let's create a unified recursive configuration like this:

```yaml
g1:
  type: group
  dependsOn:
    j1: {}
    g2: {}
    j3:
      dependOn: 
         j6: {}
         j7:
            params: 
                 a: b
                 c: d
g2: 
  type: group
  dependsOn: 
    j4: {}
    j5: {}
```
