### ISSUE TITLE
Distinguish between repeating an unique jobs in job graphs

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-job#113]
Currently a config like this will run `j2` only once, as graph node uniqueness is determined by the job name only:
```yaml
g1:
  type: group
  jobs:
     j1:
       dependsOn:
          - j2 
     j3:
       dependsOn:
          - j2:
               params:
                    a: b
```
We can improve that by making parameters a part of the job "key" (a possible encoding scheme is described in #99).
