### ISSUE TITLE
Exec command: Order and repetition of jobs

### ISSUE THREAD

**Issue by dkoyro** [bootique/bootique-job#15]
Talking about ```--exec``` command it would be useful to preserve the execution order and repetition of jobs came from the program arguments as ```--job``` options.

**Comment by atomashpolskiy** [comment]
I'd say the most simple and straight-forward solution would be to add an extra option for `--exec` command, which will trigger sequential execution. @andrus , you OK with this?

**Comment by andrus** [comment]
I don't think it even needs to be an option. It can be the default and only behavior.

**Comment by atomashpolskiy** [comment]
Seems like it's kind of orthogonal to your own design (see ExecCommand and
your comment). Why use a Spring scheduler then?

Second thought - why not just run several execs one by one?

**Comment by andrus** [comment]
you are right ... parallel execution is the default. Forgot about that (I only focused on the order of command line flags). So yeah, a "--serial" option is a good idea.

**Comment by andrus** [comment]
Another recent idea is to define job dependencies in JobMetadata and do the automated ordering via topological sorting of the dependency graph.. Worth a discussion...

**Comment by atomashpolskiy** [comment]
As discussed, we're going to add a notion of "job groups". A job group is a collection of jobs, which may (optionally) depend on each other and should be executed as a batch. The particular order of execution is going to be determined by Bootique based on the job group definition. Job group definition is basically a directed acyclic graph and may be represented in YAML in the following way:

```yaml
jobs:
  j1:
     param1: x
     param2: y
  g1:
    type: group
    jobs:
      - j1:
        dependsOn:
          - j2
          - j3
      - j2:
        dependsOn:
          - j3
```

Running a job group is similar to running a single job:
`--exec -job=g1`
Or `--g1`, when we switch to using jobs as commands.

**Comment by atomashpolskiy** [comment]
After taking a closer look at Jackson's deserialization possibilities, it looks like it's not possible to deserialize this kind of config natively. The reason being that Jackson can't "unflatten" j1's params. This would not be a problem if we used an explicit `params` property, like:
```yaml
jobs:
  j1:
    params:
      param1: x
      param2: y
```

As a bonus, this would also allow us to:
1) Specify `params` for elements of a job group
```yaml
jobs:
  g1:
    type: group
    jobs:
      j1:
        params:
          p1: x
          p2: y
        dependsOn:
          - j2
          - j3
      j2:
        dependsOn:
          - j3
```

2) Specify "default" dependencies for stand-alone jobs:
```yaml
jobs:
  j1:
    params:
      param1: x
      param2: y
    dependsOn:
      - j2
      - j3
```

3) Combine (1) and (2) to provide "default" job configurations to make job group definitions more compact

@andrus , let me know your thoughts
