### ISSUE TITLE
Job groups are not listed with "--list"

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-job#25]
Doesn't look like `--list` shows job groups defined in yaml. It only prints actual jobs.

**Comment by andrus** [comment]
Reopening...
@atomashpolskiy : I tested this in a real app with the following setup:

```java
JobModule.contributeJobs(binder).addBinding().to(MyJob.class);
```
```yaml
jobs:
  linkmove-all:
    type: group
    jobs:
      my: {}
```

So I'd expect `--list` to print

```
Available jobs:
     - linkmove-all
     - my
```

Instead it prints:

```
Available jobs:
     - my
     - my
```
