### ISSUE TITLE
Switch TriggerDescriptor properties to value objects

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-job#66]
Here is a subset of job scheduler configuration related to `TriggerDescriptor`

```yaml
cron: <string>
fixedDelayMs: <long>
fixedRateMs: <long>
initialDelayMs: <long>
```
We need to change these properties to use `Cron` (see #65 ) and `Duration` (see https://github.com/bootique/bootique/issues/219) value objects. Since Duration can be expressed in various units, we also need to rename properties that end in "Ms" (with full deprecation). So the resulting set of properties will look like this:

```yaml
cron: # Cron String
fixedDelay: # Duration String
fixedDelayMs: # deprecated, Long, internally converted to Duration
fixedRate: # Duration String
fixedRateMs: # deprecated, Long, internally converted to Duration
initialDelay: # Duration String
initialDelayMs: # deprecated, Long, internally converted to Duration
```
