### ISSUE TITLE
a few triggers for the same job with different set of parameters

### ISSUE THREAD

**Issue by akoira** [bootique/bootique-job#79]
In my project I need to schedule the same job a few times but with different set of parameters.
Something like this:
```
scheduler:
  threadPoolSize: 4
  triggers:
    - trigger: job1-2019
      job: job1
      cron: 0 * * * * ?
      params:
        param1: 2019
    - trigger: job1-2020
      job: job1
      cron: 30 * * * * ?
      params:
        param1: 2020
```
The current implementation allows to define parameters only in the "jobs" section. But in this case 
both triggers use the same parameters. 

I have reviewed this code and see I need adjust only two classes to get this functionality:
* io.bootique.job.scheduler.TriggerDescriptor - just add new property   Map<String, Object> params with @BQConfigProperty annotation 
* io.bootique.job.scheduler.DefaultScheduler:scheduleTrigger:152 -
```
return schedule(job, tc.getParams(), schedule.getTrigger());
```

May be it could be useful feature for everyone. Also it is possible that this way is wrong and I don't see the "generic" logic of this config structure and don't see some issues related with that.   

Now I am preparing this pull request in my fork.
