### ISSUE TITLE
Removing API deprecated prior to 1.0

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-job#82]
There's a number of API elements and configuration properties that were deprecated prior to 1.0 final. Let's remove them in 2.0.

## Upgrade Notes

This change affects the following trigger configuration properties, replacing milliseconds-based configs with duration-based analogs (durations can contain units, e.g. "5ms", "6sec", etc.)

* `scheduler.triggers.fixedRateMs` becomes `scheduler.triggers.fixedRate`
* `scheduler.triggers.fixedDelayMs` becomes `scheduler.triggers.fixedDelay`
* `scheduler.triggers.initialDelayMs` becomes `scheduler.triggers.initialDelay`

So

```
scheduler:
  triggers:
    - job: j1
      trigger: t1
      initialDelayMs: 10
      fixedDelayMs: 10000
```

becomes

```
scheduler:
  triggers:
    - job: j1
      trigger: t1
      initialDelay: 10ms
      fixedDelay: 10sec
```
